name: Deployment
on:
  push:
    branches:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependecies-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Testing app
        run: echo Testing success...
  Lint:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependecies-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Linting app
        run: npm run lint
  Build:
    runs-on: ubuntu-latest
    needs: Lint
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Caching dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: dependecies-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Building app
        run: npm run build:prod
      - name: Deploy app
        run: echo Deploying success...
